# Generated by Django 3.2 on 2022-05-16 14:58

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('summary', models.TextField(blank=True)),
                ('cover_image', cloudinary.models.CloudinaryField(default='placecholder', max_length=255, verbose_name='image')),
                ('public_status', models.IntegerField(choices=[(0, 'Private'), (1, 'Public'), (2, 'Awaits')], default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_creator', to=settings.AUTH_USER_MODEL)),
                ('chefs_kisses', models.ManyToManyField(blank=True, related_name='recipe_chefs_kiss', to=settings.AUTH_USER_MODEL)),
                ('ingredients', models.ManyToManyField(related_name='recipe_item', to='cook_ebook.Ingredient')),
                ('method', models.ManyToManyField(related_name='recipe_step', to='cook_ebook.Method')),
                ('tags', models.ManyToManyField(blank=True, related_name='recipe_tag', to='cook_ebook.Tag')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
