# Generated by Django 3.2 on 2022-05-17 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cook_ebook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='slug',
        ),
    ]
