# Generated by Django 3.2 on 2022-05-19 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cook_ebook', '0004_alter_tag_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='color',
        ),
    ]
