# Generated by Django 3.2 on 2022-05-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook_ebook', '0007_alter_recipe_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='summary',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
