# Generated by Django 3.2 on 2022-05-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook_ebook', '0009_auto_20220523_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=80), max_length=200, unique=True),
        ),
    ]
