# Generated by Django 3.2 on 2022-05-27 17:58

import cook_ebook.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook_ebook', '0010_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default=cook_ebook.models.random_slug, max_length=200, unique=True),
        ),
    ]
